### ISSUE TITLE
Stance Bar not showing up when triggering action bars.

### ISSUE THREAD

**Issue by XilverGG** [Repooc/ElvUI_ActionBarBuddy#12]
This is something that didn't happen in 1.34

When I mouseover Stance Bar, Action Bars show up.

https://i.imgur.com/GTb15bU.png

But it's not the same when I mousever Action Bars:

https://i.imgur.com/IkSiwdB.png

**Comment by Repooc** [comment]
cant compare 1.34 to 2.3 as stance and petbars werent an option then

**Comment by Repooc** [comment]
2.4 should be available soon for that fix
