### ISSUE TITLE
Packaged github releases

### ISSUE THREAD

**Issue by Brixus3** [Repooc/ElvUI_ActionBarBuddy#3]
Any chance packaged releases could be implemented to support the cursebreaker addon manager?

**Comment by Repooc** [comment]
i prefer downloads be made via curse or wowup as authors, we get points/credit for the downloads which in turn helps supports us authors.  Every little bit helps which is why I do not host on wowinterface for example.

**Comment by Repooc** [comment]
Cursebreaker supports downloading wago addons as mentioned in the Readme https://github.com/AcidWeb/CurseBreaker

**Comment by Repooc** [comment]
I was on my way to work when i responded, here is the syntax for wago for cursebreaker
Wago Addons: `https://addons.wago.io/addons/[addon_name]`, `wa:[addon_name]`

**Comment by Repooc** [comment]
https://addons.wago.io/addons/actionbar-buddy-elvui-plugin

**Comment by Brixus3** [comment]
Excellent, thank you for your hard work.
