### ISSUE TITLE
Cataclysm update

### ISSUE THREAD

**Issue by baliand606** [Repooc/ElvUI_ActionBarBuddy#6]
Hello, thanks for your works ! You solve my action bar pb with my hunt in Wotlk ^^
Do you prepare an update for cata ?

**Comment by Repooc** [comment]
should work in cata but just need to click load out of date addons... i will make the toc for it shortly and should be available soon

**Comment by baliand606** [comment]
Ok cool :) 
I see the option of this addon on ELVUI but all of the options, bouton, triggers have no effet... The addon is here but it doesn't work...

**Comment by Repooc** [comment]
you need to be specific on what u are trying to do and what options are selected and such... starting with testing after doing `/edebug on` and enabling just actionbar buddy after the ui reloads and showing options for the bar and ab buddy

**Comment by Repooc** [comment]
https://github.com/Repooc/ElvUI_ActionBarBuddy/assets/1479745/4d4229b9-6b99-4fbd-8d3a-cd0b938d7b59

seems fine to me

**Comment by baliand606** [comment]
Ok with your modifications and your tutorial it's working ! Thanks a lot ;)
