### ISSUE TITLE
11.0.2 seems to have broken Action Bar Buddy.

### ISSUE THREAD

**Issue by Vilacard** [Repooc/ElvUI_ActionBarBuddy#8]
I get 3 LUA errors:

Message: Interface/AddOns/ElvUI_ActionBarBuddy/Core.lua:16: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Tue Aug 13 20:17:21 2024
Count: 1
Stack: Interface/AddOns/ElvUI_ActionBarBuddy/Core.lua:16: attempt to call global 'GetAddOnMetadata' (a nil value)

Locals: 

Message: Interface/AddOns/ElvUI_ActionBarBuddy/Options.lua:141: bad argument #1 to 'tinsert' (table expected, got nil)
Time: Tue Aug 13 20:17:21 2024
Count: 1
Stack: Interface/AddOns/ElvUI_ActionBarBuddy/Options.lua:141: bad argument #1 to 'tinsert' (table expected, got nil)

Locals: 

Message: ...ElvUI_ActionBarBuddy/Modules/Changelog/Changelog.lua:188: bad argument #2 to 'format' (string expected, got nil)
Time: Tue Aug 13 20:17:35 2024
Count: 1
Stack: ...ElvUI_ActionBarBuddy/Modules/Changelog/Changelog.lua:188: bad argument #2 to 'format' (string expected, got nil)
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:508: in function `RaidFrame_LoadUI'
[string "@Interface/AddOns/Blizzard_RaidFrame/RaidFrame.lua"]:55: in function <Interface/AddOns/Blizzard_RaidFrame/RaidFrame.lua:50>

Locals:

**Comment by Repooc** [comment]
make sure to update, sorry didnt see this ticket
